name: build-deploy
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Clone repository 
      uses: actions/checkout@v4
    - name: deploy
      run: docker compose -f ci.docker-compose.yml 
